### ISSUE TITLE
[lightningglas] Weird crash?

### ISSUE THREAD

**Issue by BioTechproject27** [legopitstop/Fabric#10]
### What mod are you using?

lightningglas

### Describe the bug

MC crashes when trying to create world in SP.
[crash-2023-11-30_17.40.43-client.txt](https://github.com/legopitstop/Fabric/files/13515483/crash-2023-11-30_17.40.43-client.txt)

### Steps To Reproduce

- Open fresh Fabric install with lightningglas installed
- Click Singleplayer
- MC crashes

### Expected behavior

no crash, duh

### Minecraft Version

1.20.1

### Mod Version

fabric 1.1.0

### Platform

Win 10

**Comment by legopitstop** [comment]
Thank you for your bug report! I've updated fabric-1.1.0 (post on Curseforge and Modrinth) to not include 1.20.1 and 1.20 as this seems to only be an issue on 1.20.1 but does work on 1.20.2. Please use fabric-1.0.0 until I can release a dedicated version for 1.20.1.

**Comment by BioTechproject27** [comment]
Thanks for the quick reply, I was already worried that perhaps some of my minecraft files were corrupted or sth as this error was new to me and I had issues with some other mods already, but that is a bit relieving to read lmao

Also I wanted to ask what exactly is different from 1.0.0 to 1.1.0?

**Comment by legopitstop** [comment]
1.1.0 added better fulgurites (Generates a root-like system vs the single block that would get replaced.) and more customizability when creating your own fulgurites through datapacks or other mods.

**Comment by BioTechproject27** [comment]
Yep, 1.0.0 works fine.
However I can't get a fulgurite datapack to work...?
Inside "saves/Test/datapacks/test/data/fulgurites" I have a .json file with your log-to-coal example...
And in "saves/Test/datapacks/test" I have a pack.mcmeta file with pack format 15...
Did I miss sth

**Comment by BioTechproject27** [comment]
> 1.1.0 added better fulgurites (Generates a root-like system vs the single block that would get replaced.) and more customizability when creating your own fulgurites through datapacks or other mods.

Oh well that explains it, I had already guessed. I'll have to wait a bit then, thank you <3

**Comment by legopitstop** [comment]
You will need to use the legacy format for the fulgurites. You can find the legacy fulgurite format here https://github.com/legopitstop/Fabric/wiki/Lightning_Bolt_Glass_Legacy

**Comment by BioTechproject27** [comment]
Ah thanks.
I'll wait for the upgraded 1.20.1 version tho, want myself some cool roots :D

**Comment by legopitstop** [comment]
I've now released a dedicated 1.1.0 version for 1.20.1. Downloads:
- [Curseforge](https://curseforge.com/minecraft/mc-mods/lightning-bolt-glass/files/4915966)
- [Modrinth](https://modrinth.com/mod/lightning-bolt-glass/version/fabric-1.20.1-1.1.0)

**Comment by BioTechproject27** [comment]
so uh, https://github.com/legopitstop/Fabric/wiki/Lightning_Bolt_Glass should work with lightningglass-1.20.1-1.1.0 right?

I use the same datapack as before and it won't work.. :o
It creates the glass and orange glass roots from sand & red_sand just fine, but it doesn't convert whatever I put in my datapack, all that is just flat out ignored
other parts of the datapack that modify vanilla things (like tags n stuff) work tho

**Comment by legopitstop** [comment]
Yes it should work. 

Could you send the datapack / fulgurite file that you're using? Are you sure that the datapack is being loaded (pack.mcmeta has no errors). Also, check the console for any errors when loading the world.

**Comment by BioTechproject27** [comment]
>  Are you sure that the datapack is being loaded (pack.mcmeta has no errors)

Since other parts of the datapack work I'm pretty sure. And there seem to be no errors in the logs
I've zipped the pack (other parts also work when zipped, I've tested both)
[test.zip](https://github.com/legopitstop/Fabric/files/13533462/test.zip)

**Comment by BioTechproject27** [comment]
[latest.log](https://github.com/legopitstop/Fabric/files/13533488/latest.log)

**Comment by legopitstop** [comment]
ok, Found the issue. The json is in `data/fulgurites/new_sand.json` but should be in `data/NAMESPACE/fulgurites/new_sand.json`. 

Also note that it may not work as it will only generate the first fulgurite that passes the predicate. If you want to override the built-in fulgurites use [data/lightning_glass/fulgurites/sand.json](https://github.com/legopitstop/Fabric/tree/main/Lightning_Bolt_Glass/src/main/resources/data/lightning_glass/fulgurites) instead

**Comment by BioTechproject27** [comment]
Ahhhh, it all works as I want now, tysm!!
