### ISSUE TITLE
[poses] armor stand poses not  working

### ISSUE THREAD

**Issue by fiflak808** [legopitstop/Fabric#18]
### What mod are you using?

armor stand poses

### Describe the bug

its basically not working, I cant move the armor stand and, it doesnt look like its supposed to be

### Steps To Reproduce

1.
2.
3.
...

### Expected behavior

to work

### Minecraft Version

1.20.1

### Mod Version

1.0.0

### Platform

windows

**Comment by legopitstop** [comment]
1.0.0 is known for crashing on servers. Please use [1.0.1 for 1.20.2](https://www.curseforge.com/minecraft/mc-mods/armor-stand-poses/files/5022929)

If you're not using it on a server. Make sure you have no other armor stand mods installed and if it is still not working please describe what feature isn't working for you.

> I currently have no plans to backport my mods for older versions.
