### ISSUE TITLE
(moregold) Black on Golden Fruit Crop & Golden Fruit Sapling

### ISSUE THREAD

**Issue by Volery39** [legopitstop/Fabric#2]
### What mod are you using?

More Gold

### Describe the bug

When you place golden fruit seeds on farmland there's black on the texture

### Steps To Reproduce

1.Place Farmland
2.Plant Golden Fruit
3.See the bug
...

### Expected behavior

The black should be transparent

### Minecraft Version

the bug is on all versions

### Mod Version

the bug is on all versions

### Platform

the bug is on all platforms (i don't know about bedrock)

### Additional context

To fix this you need to add a client class, for fabric you can find it in the template mod you can download, then rename it to the mod's name and in there register the golden fruit crop as a cotout.
If you need more information you can look either on Kaupenjoe's channel on the tutorial on how to add crops or on the Fabric wiki.
When you fix this you need to change the banner of the mod on modrinth because that's where i first noticed the bug.

**Comment by legopitstop** [comment]
Also effects Golden Fruit Sapling

**Comment by legopitstop** [comment]
Fixed in [1.20.1-v1.0.1](https://legacy.curseforge.com/minecraft/mc-mods/more-gold/files/4691115)
